Candle/Candle/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf.urls.static import static
from .import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('main.urls')),
    path('users/',include('users.urls')),
    path('experts/',include('experts.urls')),
    path('courses/',include('courses.urls')),
    
] + static(settings.MEDIA_URL,document_root =settings.MEDIA_ROOT)   

Candle/courses/urls.py
from django.urls import path
from .import views

app_name ='courses'

urlpatterns= [

    path('add/course/',views.add_course_view,name='add_course_view'),
    path('add/course/content/<course_id>',views.add_course_content,name='add_course_content'),
    path('all/courses/',views.all_courses,name='all_courses'),
    path('my/courses/added/<user_id>/',views.expert_course,name='expert_course'),
    path('delete/course/<course_id>/',views.delete_course,name='delete_course'), 
    path('update/course/<course_id>/',views.update_course,name='update_course'),
    path('course/detile/<course_id>',views.course_detile_view,name='course_detile_view'),
    path('subscribed-courses/',views.subscribed_courses, name='subscribed_courses'),
    path('delete/course/content/<content_id>/',views.delete_course_content,name='delete_course_content')
]

Candle/main/urls.py
from django.urls import path
from .import views

app_name = 'main'

urlpatterns = [
    path('',views.home_view,name='home_view'),
    path('no_premissions/',views.no_premissions,name='no_premissions'),
]

Candle/courses/models.py
from django.db import models
from django.contrib.auth.models import User
import datetime
# Create your models here.

class Course(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    subcriptions = models.ManyToManyField(User, related_name="subscriptions")
    title = models.CharField(max_length=255)
    image = models.ImageField(upload_to='images/',default="images/default.jpg")
    description = models.TextField()
    addition_time = models.DateTimeField(auto_now_add=True)

    def __str__(self) -> str:
        return self.title


class CourseContent(models.Model):
    course = models.ForeignKey(Course,on_delete=models.CASCADE)
    video_title =models.CharField(max_length=255)
    description = models.TextField()
    video_file = models.FileField(upload_to='videos/',default='videos/default.mp4')

    def __str__(self) -> str:
        return self.video_title

Candle/courses/views.py
from django.shortcuts import render,redirect
from django.http import HttpRequest
from .models import Course,CourseContent
from django.contrib.auth.models import User
# Create your views here.


def add_course_view(request:HttpRequest):
    
    msg=None
    
    if request.user.is_authenticated and request.user.has_perm('courses.add_course'):

        if request.method == 'POST':
            if request.user.is_authenticated :
                try:
                    add_course =Course(user=request.user, title=request.POST['title'],description=request.POST['description'],image=request.FILES['image'])
                    add_course.save()
                    
                except Exception as e:
                    msg=e
                return redirect('courses:expert_course',request.user.id)
    else:
        return redirect("main:no_premissions")

    return render(request,'courses/add_course.html',{'msg':msg})


def add_course_content(request:HttpRequest,course_id):
    msg=None
    try:
        course =Course.objects.get(id=course_id)
    except Exception as e:
        msg =e
    if request.user.is_authenticated and request.user.has_perm('courses.add_coursecontent'):
        if request.method=='POST':
            if request.user.is_authenticated:
                try:
                    course_content = CourseContent(course=course,video_title=request.POST['video_title'],description=request.POST['description'],video_file=request.FILES['video_file'])
                    course_content.save()
                except Exception as e:
                    msg =e
            return redirect('courses:course_detile_view',course_id)
    else: return redirect("main:no_premissions")

    return render(request,'courses/add_course_content.html',{'course':course,'msg':msg})

def all_courses(request:HttpRequest):

    msg=None
    
    try:
        
        course = Course.objects.all()
    except Exception as e:
        msg =e

    return render(request,'courses/all_courses.html',{'courses':course,'msg':msg})

def expert_course(request:HttpRequest,user_id):
    expert_course=''
    msg =None
    if request.user.is_authenticated:
        try:
            expert_course=Course.objects.filter(user=user_id)
        except Exception as e:
            msg=e
        return render(request,"courses/expert_course.html",{"expert_courses":expert_course,'msg':msg})
    else:
        return redirect('main:no_premissions')
    
def delete_course(request:HttpRequest,course_id):

    msg=None
    if request.user.is_authenticated and request.user.has_perm('courses.delete_course'):
        try:
            course=Course.objects.get(id=course_id)
            course.delete()
        except Exception as e :
            msg=e
        return redirect('courses:expert_course',request.user.id)
    else: return redirect('main:no_premissions')


def update_course(request:HttpRequest,course_id):

    msg=None
    try:
        course =Course.objects.get(id=course_id)
        if request.user.is_authenticated and request.user.has_perm('courses.add_course'):
            if request.method =='POST':
                course.title=request.POST['title']
                course.description = request.POST['description']
                if 'image' in request.FILES:
                    course.image=request.FILES['image']
                
                course.save()
                return redirect('courses:expert_course',request.user.id)
        else: return redirect('main:no_premissions')
    except Exception as e:
        msg = e

    
    return render(request,'courses/update_course.html',{'course':course,'msg':msg})


def course_detile_view(request:HttpRequest,course_id):

    msg=None
    try:
        course = Course.objects.get(id=course_id)
        course_content = CourseContent.objects.filter(course=course)
        if request.method == 'POST':
            if request.user.is_authenticated:
                if 'subscribe' in request.POST:
                    course.subcriptions.add(request.user)
    except Exception as e:
        msg=e

    return render(request,'courses/course_detile.html',{'course_content':course_content,'course':course,'msg':msg})


def subscribed_courses(request:HttpRequest):
    user = request.user
    msg =None
    try:
        subscribed_courses = user.subscriptions.all()

        if request.user.is_authenticated:
            if request.method == 'POST':
                
                course_id_to_unsubscribe = request.POST.get('unsubscribe_course_id')
                if course_id_to_unsubscribe:
                    course = course_id_to_unsubscribe
                    user.subscriptions.remove(course)
    except Exception as e:
        msg = e

    return render(request, 'courses/subscribed_courses.html', {'subscribed_courses': subscribed_courses,'msg':msg})



def delete_course_content(request:HttpRequest,content_id):
    course_content=''
    msg=None
    if request.user.is_authenticated and request.user.has_perm('courses.delete_course'):
        try:
            course_content= CourseContent.objects.get(id=content_id)
            course_id=course_content.course.id
            course_content.delete()
        except Exception as e :
            msg=e
        return redirect('courses:course_detile_view',course_id)
    else: return redirect('main:no_premissions')
   

Candle/courses/templates/courses/add_course.html
{% extends 'main/base.html' %}
{% load static %}

{% block title %}Courses{% endblock %}


{% block content %}
<div class="container" >
    <div class="row" >
        <div class="col" >
            <section class="p-5 w-100" style="background-color: #eee; border-radius: .5rem .5rem 0 0;">
                <div class="row">
                  <div class="col-12">
                    <div class="card text-black" style="border-radius: 25px;">
                      <div class="card-body p-md-5">
                        <div class="row justify-content-center">
                          <div class="col-md-10 col-lg-6 col-xl-5 order-2 order-lg-1">
          
                            <p class="text-center h1 fw-bold mb-5 mt-4">Add Course</p>
                            {% if msg %}
                            <p style="color: red;">{{msg}}</p>
                            {% endif %}
                            
                            <form action="{% url 'courses:add_course_view' %}" method="POST" enctype="multipart/form-data">
                              {% csrf_token %}

                              <div class="d-flex flex-row align-items-center mb-4">
                                <i class="fas fa-user fa-lg me-3 fa-fw"></i>
                                <div class="form-outline flex-fill mb-0">
                                    
                                  <label class="form-label" for="form3Example1c">Course Title</label>
                                  <input type="text" id="form3Example1c" name="title" class="form-control" required >

                                </div>
                              </div>
                              <div class="d-flex flex-row align-items-center mb-4">
                                <i class="fas fa-user fa-lg me-3 fa-fw"></i>
                                <div class="form-outline flex-fill mb-0">
                                    
                                  <label class="form-label" for="form3Example1c">description</label>
                                  <input type="text" id="form3Example1c" name="description" class="form-control" required >

                                </div>
                              </div>
          
          
                              <div class="d-flex flex-row align-items-center mb-4">
                                <i class="fas fa-lock fa-lg me-3 fa-fw"></i>
                                <div class="form-outline flex-fill mb-0">
                                  <label class="form-label" for="form3Example4c">Course Avatar</label>
                                  <input type="file" id="form3Example4c" name="image" class="form-control" required>
                                </div>
                              </div>
          
          
                              <div class="d-flex justify-content-center mx-4 mb-3 mb-lg-4">
                                <button type="submit" class="btn btn-primary btn-lg">Create Course</button>
                              </div>
          
                            </form>
          
                          </div>
                          <div class="col-md-10 col-lg-6 col-xl-7 d-flex align-items-center order-1 order-lg-2">
          
                            <img src="https://mdbcdn.b-cdn.net/img/Photos/new-templates/bootstrap-registration/draw1.webp" class="img-fluid" alt="Sample image">
          
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </section>
        </div>
    </div>
</div>
{% endblock %}

Candle/courses/templates/courses/add_course_content.html
{% extends 'main/base.html' %}
{% load static %}

{% block title %}Add Course Content{% endblock %}

{% block content %}
<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header bg-primary text-white text-center">
                    <h1 class="h3 mb-0">Add Course Content</h1>
                </div>
                <div class="card-body">
                    <div class="row">
                        <div class="col-md-6">
                            <h2>{{ course.title }}</h2>
                            <img src="{{ course.image.url }}" alt="{{ course.title }}" class="img-fluid mt-3">
                        </div>
                        <div class="col-md-6">
                            <form action="{% url 'courses:add_course_content' course.id %}" method="POST"
                                enctype="multipart/form-data">
                                {% csrf_token %}

                                <div class="mb-3">
                                    <label for="videoTitle" class="form-label">Video Title</label>
                                    <input type="text" id="videoTitle" name="video_title" class="form-control"
                                        required>
                                </div>

                                <div class="mb-3">
                                    <label for="videoFile" class="form-label">Add Video</label>
                                    <input type="file" id="videoFile" name="video_file" class="form-control" required>
                                </div>

                                <div class="mb-3">
                                    <label for="description" class="form-label">Description</label>
                                    <textarea class="form-control" name="description" id="description" rows="4"
                                        required></textarea>
                                </div>

                                {% if msg %}
                                <p class="text-danger">{{ msg }}</p>
                                {% endif %}

                                <div class="d-grid">
                                    <button type="submit" class="btn btn-primary btn-lg">Create Course</button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

Candle/courses/templates/courses/all_courses.html
{% extends 'main/base.html' %}
{% load static %}

{% block title %}All Courses{% endblock %}

{% block content %}

<div class="container">
    {% if courses.count != 0 %}
        <div class="row m-3">
            {% for course in courses %}
                <div class="col-md-4 mb-4">
                    <div class="card h-100">
                        <img  style=" object-fit: contain;" src="{{ course.image.url }}" class="card-img-top" alt="{{ course.title }}">
                        <div class="card-body">
                            <h4 class="card-title text-center">{{ course.title }}</h4>
                            <hr>
                            <p class="card-text">{{ course.description }}</p>
                        </div>
                        <div style="font-size:smaller" class="card-footer d-flex justify-content-between ">
                            <small class="text-muted">Added by:<img src="{{ course.user.expertprofile.avatar.url }}" alt="Avatar" width="20" height="20" class="rounded-circle">{{ course.user.first_name }} {{ course.user.last_name }}</small>
                            <small>{{course.addition_time}}</small>
                        </div>
                        <div class="text-center">
                            <a  href="{% url 'courses:course_detile_view' course.id %}" class="btn btn-sm btn-primary w-100">View Course detail</a>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    {% else %}
        <div class="alert alert-info" role="alert">
            <p>There are no courses yet.</p>
        </div>
    {% endif %}
</div>

{% endblock %}

Candle/courses/templates/courses/course_detile.html
{% extends 'main/base.html' %}
{% load static %}

{% block title %}Course Detail{% endblock %}

{% block content %}
<div class="container mt-4">
    <div class="row">
        <div class="col-md-8 text-center">
            <h1 class="mb-4">{{ course.title }}</h1>

            {% if msg %}
            <div class="alert alert-info" role="alert">
                {{ msg }}
            </div>
            {% endif %}

            <img src="{{ course.image.url }}" alt="{{ course.title }}" class="img-fluid mb-4">

            {% if request.user.is_authenticated and not perms.courses.add_course %}
                <form method="post" class="mb-3">
                    {% csrf_token %}
                    <button type="submit" name="subscribe" class="btn btn-primary">Subscribe</button>
                </form>
            {% endif %}
        </div>

        <div class="col-md-4">
            {% if request.user.is_authenticated and perms.courses.add_coursecontent and course.user.id == request.user.id %}
                <a href="{% url 'courses:add_course_content' course.id %}" class="btn btn-primary btn-block mb-3">Add Content</a>
            {% endif %}
        </div>
    </div>
<hr>
    <div class="row">
        {% for content in course_content %}
            <div class="col-md-4 mb-4">
                <div class="card">
                    <div class="card-body">
                        <h2 class="card-title">{{ content.video_title }}</h2>
                        
                        <video width="100%" height="auto" controls class="mb-3">
                            <source src="{{ content.video_file.url }}" type="video/mp4">
                            Your browser does not support the video tag.
                        </video>
                        
                        <p class="card-text">{{ content.description }}</p>
    
                        {% if request.user.is_authenticated and perms.courses.add_coursecontent %}
                            <!-- Delete Button with Modal Trigger -->
                            <button type="button" class="btn btn-danger btn-sm" data-toggle="modal" data-target="#deleteModal{{ content.id }}">
                                Delete
                            </button>

                            <!-- Delete Modal -->
                            <div class="modal fade" id="deleteModal{{ content.id }}" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel{{ content.id }}" aria-hidden="true">
                                <div class="modal-dialog" role="document">
                                    <div class="modal-content">
                                        <div class="modal-header">
                                            <h5 class="modal-title" id="deleteModalLabel{{ content.id }}">Confirm Deletion</h5>
                                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                <span aria-hidden="true">&times;</span>
                                            </button>
                                        </div>
                                        <div class="modal-body">
                                            Are you sure you want to delete "{{ content.video_title }}"?
                                        </div>
                                        <div class="modal-footer">
                                            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                                            <a href="{% url 'courses:delete_course_content' content.id %}" class="btn btn-danger">Delete</a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        {% endif %}
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

Candle/courses/templates/courses/expert_course.html
{% extends 'main/base.html' %}
{% load static %}

{% block title %}My Added Courses{% endblock %}

{% block content %}
<div class="container">
    {% if courses.count != 0 %}
        <div class="row m-3">
            {% for course in expert_courses %}
                <div class="col-md-4 mb-4">
                    <div class="card h-100">
                        <img  style=" object-fit: contain;" src="{{ course.image.url }}" class="card-img-top" alt="{{ course.title }}">
                        <div class="card-body d-flex justify-content-between">
                            <div>
                                <h4 class="card-title">{{ course.title }}</h4>
                                <p class="card-text">{{ course.description }}</p>
                                
                            </div>
                         
                        </div>
                        <div style="font-size:smaller" class="card-footer d-flex justify-content-between ">
                            <small class="text-muted">Added by:<img src="{{ course.user.expertprofile.avatar.url }}" alt="Avatar" width="20" height="20" class="rounded-circle">{{ course.user.first_name }} {{ course.user.last_name }}</small>
                            <small>{{course.addition_time}}</small>
                            
                        </div>
                        {% if request.user.is_authenticated and perms.courses.add_course and course.user.id == request.user.id %}
                        <div class="btn-group" role="group">
                            <a  href="{% url 'courses:update_course' course.id %}" class="btn btn-primary">Update</a>
                            <!-- Inside your for loop where the delete link is -->
<button type="button" class="btn btn-danger" data-toggle="modal" data-target="#deleteCourseModal{{ course.id }}">Delete</button>

<!-- Modal for Delete Confirmation (each course has a unique modal id) -->
<div class="modal fade" id="deleteCourseModal{{ course.id }}" tabindex="-1" role="dialog" aria-labelledby="deleteCourseModalLabel{{ course.id }}" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="deleteCourseModalLabel{{ course.id }}">Confirm Deletion</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                Are you sure you want to delete this course?
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                <a href="{% url 'courses:delete_course' course.id %}" class="btn btn-danger">Delete</a>
            </div>
        </div>
    </div>
</div>

                        </div>
                        {% endif %}
                        <div class="text-center">
                            <a  href="{% url 'courses:course_detile_view' course.id %}" class="filter-link btn btn-light border-20  w-100">View Course detail</a>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    {% else %}
    
        <div class="alert alert-info" role="alert">
            <p>There are no courses yet.</p>
            <a class="btn btn-sm btn-primary" href="{% url 'courses:add_course_view' %}">add course</a>
        </div>
    {% endif %}
</div>

{% endblock %}

Candle/courses/templates/courses/subscribed_courses.html
{% extends 'main/base.html' %}

{% block content %}
  <h2>Subscribed Courses</h2>

  {% if subscribed_courses.count > 0 %}
  <div class="container">
    
        <div class="row m-3">
          {% for course in subscribed_courses %}
                <div class="col-md-4 mb-4">
                    <div class="card h-100">
                        <img  style=" object-fit: contain;" src="{{ course.image.url }}" class="card-img-top" alt="{{ course.title }}">
                        <div class="card-body">
                            <h4 class="card-title text-center">{{ course.title }}</h4>
                            <hr>
                            <p class="card-text">{{ course.description }}</p>
                        </div>
                        <div style="font-size:smaller" class="card-footer d-flex justify-content-between ">
                            <small class="text-muted">Added by:<img src="{{ course.user.expertprofile.avatar.url }}" alt="Avatar" width="20" height="20" class="rounded-circle">{{ course.user.first_name }} {{ course.user.last_name }}</small>
                            <small>{{course.addition_time}}</small>
                        </div>
                        <div class="text-center">
                            <a  href="{% url 'courses:course_detile_view' course.id %}" class="btn btn-sm btn-primary w-100">View Course detail</a>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    {% else %}
        <div class="alert alert-info" role="alert">
            <p>There are no courses yet.</p>
        </div>
    {% endif %}
  </div>

{% endblock %}

Candle/courses/templates/courses/update_course.html
{% extends 'main/base.html' %}
{% load static %}

{% block title %}Update Course{% endblock %}


{% block content %}
<div class="container" >
    <div class="row" >
        <div class="col" >
            <section class="p-5 w-100" style="background-color: #eee; border-radius: .5rem .5rem 0 0;">
                <div class="row">
                  <div class="col-12">
                    <div class="card text-black" style="border-radius: 25px;">
                      <div class="card-body p-md-5">
                        <div class="row justify-content-center">
                          <div class="col-md-10 col-lg-6 col-xl-5 order-2 order-lg-1">
          
                            <p class="text-center h1 fw-bold mb-5 mt-4">Add Course</p>
                            {% if msg %}
                            <p style="color: red;">{{msg}}</p>
                            {% endif %}
                            
                            <form action="{% url 'courses:update_course' course.id %}" method="POST" enctype="multipart/form-data">
                              {% csrf_token %}

                              <div class="d-flex flex-row align-items-center mb-4">
                                <i class="fas fa-user fa-lg me-3 fa-fw"></i>
                                <div class="form-outline flex-fill mb-0">
                                    
                                  <label class="form-label" for="form3Example1c">Course Title</label>
                                  <input type="text" id="form3Example1c" name="title" value="{{course.title}}" class="form-control">

                                </div>
                              </div>
                              <div class="d-flex flex-row align-items-center mb-4">
                                <i class="fas fa-user fa-lg me-3 fa-fw"></i>
                                <div class="form-outline flex-fill mb-0">
                                    
                                  <label class="form-label" for="form3Example1c">description</label>
                                  <input type="text" id="form3Example1c" value="{{course.description}}" name="description" class="form-control" required >

                                </div>
                              </div>
          
          
                              <div class="d-flex flex-row align-items-center mb-4">
                                <i class="fas fa-lock fa-lg me-3 fa-fw"></i>
                                <div class="form-outline flex-fill mb-0">
                                  <label class="form-label" for="form3Example4c">Course Avatar</label>
                                  <input type="file" id="form3Example4c" name="image" class="form-control">
                                </div>
                              </div>
          
          
                              <div class="d-flex justify-content-center mx-4 mb-3 mb-lg-4">
                                <button type="submit" class="btn btn-primary btn-lg">Update Course</button>
                              </div>
          
                            </form>
          
                          </div>
                          <div class="col-md-10 col-lg-6 col-xl-7 d-flex align-items-center order-1 order-lg-2">
          
                            <img src="https://mdbcdn.b-cdn.net/img/Photos/new-templates/bootstrap-registration/draw1.webp" class="img-fluid" alt="Sample image">
          
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </section>
        </div>
    </div>
</div>
{% endblock %}