Candle/Candle/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf.urls.static import static
from .import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('main.urls')),
    path('users/',include('users.urls')),
    path('experts/',include('experts.urls')),
    path('courses/',include('courses.urls')),
    
] + static(settings.MEDIA_URL,document_root =settings.MEDIA_ROOT)   

Candle/courses/urls.py
from django.urls import path
from .import views

app_name ='courses'

urlpatterns= [

    path('add/course/',views.add_course_view,name='add_course_view'),
    path('add/course/content/<course_id>',views.add_course_content,name='add_course_content'),
    path('all/courses/',views.all_courses,name='all_courses'),
    path('my/courses/added/<user_id>/',views.expert_course,name='expert_course'),
    path('delete/course/<course_id>/',views.delete_course,name='delete_course'), 
    path('update/course/<course_id>/',views.update_course,name='update_course'),
    path('course/detile/<course_id>',views.course_detile_view,name='course_detile_view'),
    path('subscribed-courses/',views.subscribed_courses, name='subscribed_courses'),
    path('delete/course/content/<content_id>/',views.delete_course_content,name='delete_course_content')
]

Candle/experts/urls.py
from django.urls import path
from .import views

app_name = 'experts'

urlpatterns = [
    path('experts/',views.experts_view,name='experts_view'),
    
    
]

Candle/main/urls.py
from django.urls import path
from .import views

app_name = 'main'

urlpatterns = [
    path('',views.home_view,name='home_view'),
    path('no_premissions/',views.no_premissions,name='no_premissions'),
]

Candle/users/urls.py
from django.urls import path
from . import views

app_name ='users'

urlpatterns = [
    path('logup/',views.logup_view,name='logup_view'),
    path('login/',views.login_view,name='login_view'),
    path('logout/',views.logout_view,name='logout_view'),
    path('profile/<user_id>/',views.profile_view,name='profile_view'),
    path('update/profile/',views.update_profile_view,name='update_profile_view'),
    path('add/experiece/<user_id>/',views.add_experience,name='add_experience'),
    path('delete/experience/<experience_id>/',views.delete_experience,name='delete_experience')
    
]

Candle/courses/models.py
from django.db import models
from django.contrib.auth.models import User
import datetime
# Create your models here.

class Course(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    subcriptions = models.ManyToManyField(User, related_name="subscriptions")
    title = models.CharField(max_length=255)
    image = models.ImageField(upload_to='images/',default="images/default.jpg")
    description = models.TextField()
    addition_time = models.DateTimeField(auto_now_add=True)

    def __str__(self) -> str:
        return self.title


class CourseContent(models.Model):
    course = models.ForeignKey(Course,on_delete=models.CASCADE)
    video_title =models.CharField(max_length=255)
    description = models.TextField()
    video_file = models.FileField(upload_to='videos/',default='videos/default.mp4')

    def __str__(self) -> str:
        return self.video_title

Candle/main/views.py
from django.shortcuts import render
from django.http import HttpRequest

# Create your views here.

def home_view(request:HttpRequest):

    return render(request,'main/home.html')


def no_premissions(request:HttpRequest):

    return render(request,'main/no_premissions.html')

Candle/main/templates/main/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <link
    rel="stylesheet"
    href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css"
  />
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200" />
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <title>{% block title %}{% endblock %}</title>
    
    
</head>
<body>
    <div class="header" >
        <nav class="navbar navbar-expand-lg bg-body-tertiary d-flex justify-content-between">
            <div class="container-fluid">
              <img src="{% static 'images/candle.jpg' %}" alt="Your Logo" width="40" height="40" class="d-inline-block align-top rounded-circle img-brand">
              <a class="navbar-brand" href="#">Candle</a>
              <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>
              <div class="collapse navbar-collapse" id="navbarNavDropdown">
                <ul class="navbar-nav">
                  <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'main:home_view' %}">Home</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'experts:experts_view' %}">Experts</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'courses:all_courses' %}">View Courses</a>
                  </li>
                  {% if request.user.is_authenticated %}
                  <li><a class="nav-link m-0" href="{% url 'users:profile_view'  request.user.id %}">welcome, {{ request.user.username }}</a>
                  </li>
                  <li><a href="{% url 'users:logout_view' %}"><span class="material-symbols-outlined">
                    logout
                    </span></a></li>

                  {% else %}
                  <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                      Join Us
                    </a>
                    <ul class="dropdown-menu">
                      <li><a class="dropdown-item" href="{% url 'users:logup_view' %}">Log Up</a></li>
                      <li><a class="dropdown-item" href="{% url 'users:login_view' %}">Log In</a></li>
                      <li><a class="dropdown-item" href="#">Something else here</a></li>
                    </ul>
                  </li>
                  {% endif %}
                </ul>

              </div>
              {% if request.user.is_authenticated and  not  perms.courses.add_course %}
              <a class="nav-link m-0" href="{% url 'courses:subscribed_courses'%}">Subscribed Courses</a>
              {% endif %}
              {% if request.user.is_authenticated and perms.courses.add_course %}
              <div>
                <ul class="navbar-nav">
                  <li><a class="nav-link" href="{% url 'courses:expert_course' request.user.id %}">My courses</a></li>
                  <li>
                    <a class="nav-link" href="{% url 'courses:add_course_view'%}">add course</a>
                  </li>
                </ul>

              </div>
              {% endif %}
            </div>
          </nav>
    </div>
    {% block content %}

    {% endblock %}
    
</body>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>


<!-- Bootstrap JS and dependencies -->
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

<script>
  
const myModal = document.getElementById('myModal')
const myInput = document.getElementById('myInput')

myModal.addEventListener('shown.bs.modal', () => {
  myInput.focus()
})
</script>
<script>
  // Attach the course ID to the modal's delete button
  $(document).ready(function () {
      $('.btn-danger').on('click', function () {
          var courseId = $(this).data('course-id');
          $('#confirmDeleteBtn').attr('href', '{% url "courses:delete_course" 0 %}'.replace('0', courseId));
      });
  });
</script>
</html>

Candle/main/templates/main/home.html
{% extends 'main/base.html' %}
{% load static %}

{% block content %}
<div class="jumbotron jumbotron-fluid video-container">
    <video autoplay loop muted playsinline class="w-100">
      
      <source src="{% static 'videos/candle_book.mp4' %}" type="video/mp4">
      Your browser does not support the video tag 3.
    </video>
    <div class="content-overlay">
      <h1>Illuminate Your Mind</h1>
      <P>Ignite The Flame Of Knowledge With Candle,Your Learning Companion</P>
    </div>
  </div>

{% endblock %}

Candle/main/templates/main/no_premissions.html
{% extends 'main/base.html' %}
{% load static %}
{% block title %}No Permissions{% endblock %}
{% block content %}

<div class="text-center">
    <div class="display-1">403</div>
    <p class="lead">No Permissions</p>
    <a class="btn btn-primary" href="{% url 'main:home_view' %}">Back to home page</a>
</div>
{% endblock %}