Candle/Candle/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf.urls.static import static
from .import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('main.urls')),
    path('users/',include('users.urls')),
    path('experts/',include('experts.urls')),
    path('courses/',include('courses.urls')),
    
] + static(settings.MEDIA_URL,document_root =settings.MEDIA_ROOT)   

Candle/main/urls.py
from django.urls import path
from .import views

app_name = 'main'

urlpatterns = [
    path('',views.home_view,name='home_view'),
    path('no_premissions/',views.no_premissions,name='no_premissions'),
]

Candle/users/urls.py
from django.urls import path
from . import views

app_name ='users'

urlpatterns = [
    path('logup/',views.logup_view,name='logup_view'),
    path('login/',views.login_view,name='login_view'),
    path('logout/',views.logout_view,name='logout_view'),
    path('profile/<user_id>/',views.profile_view,name='profile_view'),
    path('update/profile/',views.update_profile_view,name='update_profile_view'),
    path('add/experiece/<user_id>/',views.add_experience,name='add_experience'),
    path('delete/experience/<experience_id>/',views.delete_experience,name='delete_experience')
    
]

Candle/courses/models.py
from django.db import models
from django.contrib.auth.models import User
import datetime
# Create your models here.

class Course(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    subcriptions = models.ManyToManyField(User, related_name="subscriptions")
    title = models.CharField(max_length=255)
    image = models.ImageField(upload_to='images/',default="images/default.jpg")
    description = models.TextField()
    addition_time = models.DateTimeField(auto_now_add=True)

    def __str__(self) -> str:
        return self.title


class CourseContent(models.Model):
    course = models.ForeignKey(Course,on_delete=models.CASCADE)
    video_title =models.CharField(max_length=255)
    description = models.TextField()
    video_file = models.FileField(upload_to='videos/',default='videos/default.mp4')

    def __str__(self) -> str:
        return self.video_title

Candle/users/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

Candle/users/views.py
from django.shortcuts import render,redirect
from django.http import HttpRequest
from django.contrib.auth.models import User
from django.contrib.auth import authenticate ,login,logout
from experts.models import ExpertExperience ,ExpertProfile
from django.db import IntegrityError
# Create your views here.

def logup_view(request:HttpRequest):
    msg= None
    try:
        if request.method == 'POST':
            user = User.objects.create_user(username=request.POST['username'],password=request.POST['password'],email=request.POST['email'])
            user.save()
            return redirect('users:login_view')
    except:
        msg = "something went wrong please try later"
    return render(request,'users/logup.html',{'msg':msg})

def login_view(request:HttpRequest):
    msg =None
    if request.method =='POST':
        
        user = authenticate(request,username=request.POST['username'],password=request.POST['password'])
        if user:
            login(request,user)
            return redirect('main:home_view')
        else:
            msg='please provide correct username and password'
    return render(request,'users/login.html',{'msg':msg})

def logout_view(request:HttpRequest):

    if request.user.is_authenticated:
        logout(request) 
        return redirect('users:login_view')

def profile_view(request:HttpRequest,user_id):
    msg=None
    try:
        experts=User.objects.filter(groups__name='Experts')

        user = User.objects.get(id=user_id)
        experiences = ExpertExperience.objects.filter(user=user)
    except Exception as e:

        msg=e
    
    return render(request,'users/profile.html',{"user":user,'experts':experts,'experiences':experiences})


def update_profile_view(request:HttpRequest):
    msg = None
    experience_field=None
    if request.user.has_perm('experts.add_expertexperience'):

        experience_field = ExpertProfile.experience_fields.choices
    if request.user.is_authenticated:
        if request.method == "POST":
            try:
            
                user : User = request.user
                user.first_name = request.POST["first_name"]
                user.last_name = request.POST["last_name"]
                user.email = request.POST["email"]
                user.save()

                
                try:
                    profile = request.user.expertprofile
                except Exception as e:
                    profile = ExpertProfile(user=user, bio=request.POST["bio"],experience_field=request.POST['experience_field'])
                    profile.save()


                
                if 'avatar' in request.FILES: profile.avatar = request.FILES["avatar"]
                profile.bio = request.POST["bio"]
                profile.save()

                return redirect("users:profile_view", user_id = request.user.id)
            

    
                
            except IntegrityError as e:
                msg = f"Please select another username"
            except Exception as e:

                msg = e
    else:
        return redirect("main:no_premissions")

    return render(request,'users/update.html',{'msg':msg,'experience_field':experience_field})


def add_experience(request:HttpRequest,user_id):

    expert_user =User.objects.get(id=user_id)
    if request .user.is_authenticated and request.user.has_perm('experts.add_expertexperience'):
        if request.method =='POST':

            expert_experience=ExpertExperience(user=expert_user,experience=request.POST['experience'],experience_years=request.POST['experience_years'])
            expert_experience.save()
        return redirect('users:profile_view',user_id)


def delete_experience(request:HttpRequest,experience_id):

    
    expert_experience=ExpertExperience.objects.get(id=experience_id)
    expert_experience.delete()
    return redirect('users:profile_view',request.user.id)

Candle/users/templates/users/login.html
{% extends 'main/base.html' %}

{% block title %}Sign In{% endblock %}


{% block content %}
<div class="container" >
    <div class="row" >
        <div class="col" >
            <section class="p-5 w-100" style="background-color: #eee; border-radius: .5rem .5rem 0 0;">
                <div class="row">
                  <div class="col-12">
                    <div class="card text-black" style="border-radius: 25px;">
                      <div class="card-body p-md-5">
                        <div class="row justify-content-center">
                          <div class="col-md-10 col-lg-6 col-xl-5 order-2 order-lg-1">
          
                            <p class="text-center h1 fw-bold mb-5 mt-4">Sign in</p>
                            {% if msg %}
                            <p style="color: red;">{{msg}}</p>
                            {% endif %}
                            <form action="{% url 'users:login_view' %}" method="post" >
                              {% csrf_token %}
          
                              <div class="d-flex flex-row align-items-center mb-4">
                                <i class="fas fa-user fa-lg me-3 fa-fw"></i>
                                <div class="form-outline flex-fill mb-0">
                                  <label class="form-label" for="form3Example1c">User Name</label>
                                  <input type="text" name="username" id="form3Example1c" class="form-control">
                                  
                                </div>
                              </div>
                              <div class="d-flex flex-row align-items-center mb-4">
                                <i class="fas fa-lock fa-lg me-3 fa-fw"></i>
                                <div class="form-outline flex-fill mb-0">
                                  <label class="form-label"  for="form3Example4c">Password</label>
                                  <input type="password"  name="password" id="form3Example4c" class="form-control">
                                  
                                </div>
                              </div>

          
                              <div class="d-flex justify-content-center mx-4 mb-3 mb-lg-4">
                                <button type="submit" class="btn btn-primary btn-lg">Sign In</button>
                              </div>
          
                            </form>
          
                          </div>
                          <div class="col-md-10 col-lg-6 col-xl-7 d-flex align-items-center order-1 order-lg-2">
          
                            <img src="https://mdbcdn.b-cdn.net/img/Photos/new-templates/bootstrap-registration/draw1.webp" class="img-fluid" alt="Sample image">
          
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </section>
        </div>
    </div>
</div>

{% endblock %}

Candle/users/templates/users/logup.html
{% extends 'main/base.html' %}
{% load static %}
{% block title %}Sign up{% endblock %}

{% block content %}
<div class="container" >
    <div class="row" >
        <div class="col" >
            <section class="p-5 w-100" style="background-color: #eee; border-radius: .5rem .5rem 0 0;">
                <div class="row">
                  <div class="col-12">
                    <div class="card text-black" style="border-radius: 25px;">
                      <div class="card-body p-md-5">
                        <div class="row justify-content-center">
                          <div class="col-md-10 col-lg-6 col-xl-5 order-2 order-lg-1">
          
                            <p class="text-center h1 fw-bold mb-5 mt-4">Sign up</p>
          
                            <form action="{% url 'users:logup_view' %}" method="POST">
                              {% csrf_token %}
          
                              <div class="d-flex flex-row align-items-center mb-4">
                                <i class="fas fa-user fa-lg me-3 fa-fw"></i>
                                <div class="form-outline flex-fill mb-0">
                                  <label class="form-label" for="form3Example1c">User Name</label>
                                  <input type="text" id="form3Example1c" required name="username" class="form-control">
                                  
                                </div>
                              </div>
          
                              <div class="d-flex flex-row align-items-center mb-4">
                                <i class="fas fa-envelope fa-lg me-3 fa-fw"></i>
                                <div class="form-outline flex-fill mb-0">
                                  <label class="form-label"  for="form3Example3c">Your Email</label>
                                  <input type="email" id="form3Example3c" name="email" class="form-control" required >
                                  
                                </div>
                              </div>
          
                              <div class="d-flex flex-row align-items-center mb-4">
                                <i class="fas fa-lock fa-lg me-3 fa-fw"></i>
                                <div class="form-outline flex-fill mb-0">
                                  <label class="form-label" for="form3Example4c">Password</label>
                                  <input type="password" id="form3Example4c" name="password" class="form-control" required>
                                  
                                </div>
                              </div>
          
          
          
                              <div class="d-flex justify-content-center mx-4 mb-3 mb-lg-4">
                                <button type="submit" class="btn btn-primary btn-lg">Register</button>
                              </div>
          
                            </form>
          
                          </div>
                          <div class="col-md-10 col-lg-6 col-xl-7 d-flex align-items-center order-1 order-lg-2">
          
                            <img src="https://mdbcdn.b-cdn.net/img/Photos/new-templates/bootstrap-registration/draw1.webp" class="img-fluid" alt="Sample image">
          
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </section>
        </div>
    </div>
</div>
{% endblock %}

Candle/users/templates/users/profile.html
{% extends 'main/base.html' %}

{% block title %}Profile{% endblock %}

{% block content %}

<section class="my-5">
    <div class="container profile-container">
        <div class="row">
            <div class="col-md-4">
                <!-- User Avatar -->
                <img src="{{ user.expertprofile.avatar.url }}" alt="User Avatar" class="img-fluid rounded img-thumbnail mb-3">
            </div>
            <div class="col-md-8">
                <!-- User Bio -->
                <div class="d-flex justify-content-between align-items-center mb-3">
                    <h2 class="profile-title">{{ user.username }}</h2>
                    {% if request.user.is_authenticated and request.user.id == user.id %}
                        <a class="btn btn-primary" href="{% url 'users:update_profile_view' %}">Update Profile</a>
                    {% endif %}
                </div>

                <div class="row">
                    <div class="col-md-6">
                        <h5>Bio:</h5>
                        <p class="name-label">{{ user.expertprofile.bio }}</p>
                    </div>
                    <div class="col-md-6">
                        <p class="name-label"><strong>First Name: </strong>{{ user.first_name }}</p>
                        <p class="name-label"><strong>Last Name: </strong>{{ user.last_name }}</p>
                        <p class="name-label"><strong>Email: </strong><a href="mailto:{{ user.email }}">{{ user.email }}</a></p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

{% if user in experts %}
    <div class="section my-5">
        <hr>
        <div class="container cc-education">
            <div class="d-flex justify-content-between align-items-center mb-4">
                <div class="h4 text-center title">Professional Experience</div>

                {% if request.user.is_authenticated and request.user.id == user.id %}
                    <div>
<!-- Button to trigger modal -->
<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#addExperienceModal">
    Add Experience
</button>

<!-- Modal for Add Experience -->
<div class="modal fade" id="addExperienceModal" tabindex="-1" role="dialog" aria-labelledby="addExperienceModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="addExperienceModalLabel">Add Experience</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <!-- Form for adding experience -->
                <form action="{% url 'users:add_experience' user.id %}" method="POST">
                    {% csrf_token %}
                    <div class="form-group">
                        <label for="experience">Experience:</label>
                        <input type="text" name="experience" id="experience" class="form-control" required>
                    </div>
                    <div class="form-group">
                        <label for="experience_years">Years of Experience:</label>
                        <input type="number" name="experience_years" id="experience_years" class="form-control" required>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                        <button type="submit" class="btn btn-primary">Add Experience</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

                    </div>
                {% endif %}
            </div>

            {% if experiences.count > 0 %}
                {% for ex in experiences %}
                    <div class="card mb-3">
                        <div class="row no-gutters">
                            <div class="col-md-3 bg-secondary text-center">
                                <div class="card-body cc-education-header">
                                    <h5 class="card-title">{{ ex.experience }}</h5>
                                </div>
                            </div>
                            <div class="col-md-9">
                                <div class="card-body">
                                    <div class="d-flex justify-content-between">
                                        <div>
                                            <h5 class="card-title">Experience Years</h5>
                                            <p class="card-text category">{{ ex.experience_years }}</p>
                                        </div>
                                        <div>
                                            {% if request.user.is_authenticated and request.user.id == user.id %}
                                                <button type="button" class="btn btn-danger" data-toggle="modal"
                                                    data-target="#deleteExperienceModal{{ ex.id }}">
                                                    Delete
                                                </button>
                                            {% endif %}
                                        </div>
                                    </div>

                                    <!-- Modal for Delete Confirmation -->
                                    <div class="modal fade" id="deleteExperienceModal{{ ex.id }}" tabindex="-1"
                                        role="dialog" aria-labelledby="deleteExperienceModalLabel{{ ex.id }}" aria-hidden="true">
                                        <div class="modal-dialog" role="document">
                                            <div class="modal-content">
                                                <div class="modal-header">
                                                    <h5 class="modal-title" id="deleteExperienceModalLabel{{ ex.id }}">Confirm
                                                        Deletion</h5>
                                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                        <span aria-hidden="true">&times;</span>
                                                    </button>
                                                </div>
                                                <div class="modal-body">
                                                    <p>Are you sure you want to delete this experience?</p>
                                                </div>
                                                <div class="modal-footer">
                                                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                                                    <a href="{% url 'users:delete_experience' ex.id %}" class="btn btn-danger">Delete</a>
                                                </div>
                                            </div>
                                        </div>
                                    </div>

                                </div>
                            </div>
                        </div>
                    </div>

                {% endfor %}


            {% endif %}
        </div>
    </div>
{% endif %}

{% endblock %}

Candle/users/templates/users/update.html
{% extends 'main/base.html' %}
{% load static %}
{% block title %}Update Profile{% endblock %}

{% block content %}
<div class="container" >
    <div class="row" >
        <div class="col" >
            <section class="p-5 w-100" style="background-color: #eee; border-radius: .5rem .5rem 0 0;">
                <div class="row">
                  <div class="col-12">
                    <div class="card text-black" style="border-radius: 25px;">
                      <div class="card-body p-md-5">
                        <div class="row justify-content-center">
                          <div class="col-md-10 col-lg-6 col-xl-5 order-2 order-lg-1">
          
                            <p class="text-center h1 fw-bold mb-5 mt-4">Update Profile</p>
                            {% if msg %}
                            <p style="color: red;">{{msg}}</p>
                            {% endif %}
                            <form action="{% url 'users:update_profile_view' %}" method="POST" enctype="multipart/form-data">
                              {% csrf_token %}

                              <div class="d-flex flex-row align-items-center mb-4">
                                <i class="fas fa-user fa-lg me-3 fa-fw"></i>
                                <div class="form-outline flex-fill mb-0">
                                    
                                  <label class="form-label" for="form3Example1c">First Name</label>
                                  <input type="text" id="form3Example1c" value="{{user.first_name}}" name="first_name" class="form-control">
                                                                      
                                  <label class="form-label" for="form3Example1c">Last Name</label>
                                  <input type="text" id="form3Example1c" value="{{user.last_name}}"  name="last_name" class="form-control">
                                  
                                </div>
                              </div>
                              <div class="d-flex flex-row align-items-center mb-4">
                                <i class="fas fa-envelope fa-lg me-3 fa-fw"></i>
                                <div class="form-outline flex-fill mb-0">
                                  <label class="form-label" for="form3Example3c">Your Bio:</label>
                                  <textarea class="form-control"  name="bio" id="" cols="30" rows="10">{{user.expertprofile.bio}}</textarea>
                                  
                                </div>
                              </div>
          
                              <div class="d-flex flex-row align-items-center mb-4">
                                <i class="fas fa-envelope fa-lg me-3 fa-fw"></i>
                                <div class="form-outline flex-fill mb-0">
                                  <label class="form-label" for="form3Example3c">Your Email</label>
                                  <input type="email" id="form3Example3c" value="{{user.email}}" name="email" class="form-control">
                                  
                                </div>
                              </div>
                              <div class="d-flex flex-row align-items-center mb-4">
                                <i class="fas fa-lock fa-lg me-3 fa-fw"></i>
                                <div class="form-outline flex-fill mb-0">
                                  {% if request.user.is_authenticated and perms.courses.add_coursecontent %}
                                  <label class="form-label" for="form3Example4c">Experience Field</label>
                                  {% endif %}
                                  {% for key , value in experience_field %}
                                  <div class="form-check">
                                    <input class="form-check-input" type="radio" name="experience_field" value="{{value}}" id="{{key}}">
                                    <label>
                                      {{value}}
                                    </label>
                                  </div>
                                {% endfor %}
                                </div>
                              </div>
          
                              <div class="d-flex flex-row align-items-center mb-4">
                                <i class="fas fa-lock fa-lg me-3 fa-fw"></i>
                                <div class="form-outline flex-fill mb-0">
                                  <label class="form-label" for="form3Example4c">Avatar</label>
                                  <input type="file" id="form3Example4c" name="avatar" class="form-control">
                                </div>
                              </div>
          
          
                              <div class="d-flex justify-content-center mx-4 mb-3 mb-lg-4">
                                <button type="submit" class="btn btn-primary btn-lg">Update</button>
                              </div>
          
                            </form>
          
                          </div>
                          <div class="col-md-10 col-lg-6 col-xl-7 d-flex align-items-center order-1 order-lg-2">
          
                            <img src="https://mdbcdn.b-cdn.net/img/Photos/new-templates/bootstrap-registration/draw1.webp" class="img-fluid" alt="Sample image">
          
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </section>
        </div>
    </div>
</div>
{% endblock %}